# Slack api URL
api_url: "https://slack.com/api/"

# Application port
port: 7711

# Bot token: xoxb..
token: ""

# Meeting channel name
channel_names:
  - "d"

# Meeting schedule (in crontab format with seconds)
meeting_schedule: "0 * * * * *"
